add / fix JSDoc annotations
medooze/media-server-node pull request #217
Opened 2023-10-18 20:32 UTC by mildsunrise

finally, after #216 I think I have everything ready to add / fix the JSDoc comments on the code.
I'm pretty happy with the results, very very few errors remain ^^
and I found many typos along the way (#215)

the rationale is the same than for https://github.com/medooze/semantic-sdp-js/pull/28. our current typings are so outdated they're likely misleading people at this point rather than helping. so, delete them and autogenerate them from the JSDoc comments in our code.

**not ready for review yet.** there are still some things I'd like to take out of this PR first, to ease review (a bugfix and some needed refactors)

2023-10-19 02:14 UTC, mildsunrise commented
note to self in case I hit this problem again. the tests are failing because... we're using a very old version of TAP which uses the `esm` package to simulate ESM support back when Node.js did not have it yet.

this package will, by default, use a "heuristic" to figure out if a file is ESM or CJS. the heuristic is to search for the words `import`, `export`, and so on. the module DOES NOT care if they only occur inside a comment and not in actual code. amazing. so files are now being wrongly detected as ESM and transpiled accordingly, which causes the syntax issues.

this would be solved by upgrading TAP to v15 (TAP version in other repos is 16). HOWEVER if I do that, the code breaks because the `test.done()` function no longer exists. I tried to find that function in [documentation](https://node-tap.org/api/); it is not mentioned anywhere. [neither in older versions](https://github.com/tapjs/tapjs/blob/v11.1.5/docs/api/index.md). in the [list of breaking changes for v15](https://github.com/tapjs/tapjs/blob/v15.0.0/docs/src/content/changelog/index.md#150---2021-03-30) it is also not mentioned. nevertheless it seems this [is an alias to `test.end()`]() that they decided to remove when they made their refactor and extracted functionality into libtap.

so I'll open another PR to upgrade to TAP v16 to match the other repos, and then mass rename `test.done()` to `test.end()`.

2023-10-19 12:12 UTC, murillo128 requested changes

2023-10-19 12:12 UTC, murillo128 commented on lib/IncomingStream.js
> +		const promises = [...this.tracks.values()].map(track =>
please make it a bit easier to understand, even if the code is longer. Or add some comments

2023-10-19 12:12 UTC, murillo128 commented on lib/SDPManagerPlanB.js
> +			if (!this.renegotiationNeeded && (this.state === 'initial' || this.state === 'stable'))
why?

2023-10-19 12:12 UTC, murillo128 commented on lib/IncomingStream.js
> +						const source = SharedPointer(new Native.RTPIncomingSourceGroupShared(type,this.transport.GetTimeService()));
Why are you doing this?

The Native objects are wrapped into a shared pointer automatically:

https://github.com/medooze/media-server-node/blob/master/lib/SharedPointer.js#L61

2023-10-19 15:58 UTC, mildsunrise commented on lib/ActiveSpeakerMultiplexer.js
> -			/**
this PR is not yet ready for review, and the removing of event blocks was one of the things I wanted to take out of this PR. I'll explain the motivation in the separate PR.

2023-10-19 20:49 UTC, mildsunrise commented
rebased against latest master.
this is still not ready for review.

2023-10-25 00:29 UTC, mildsunrise commented on lib/SDPManagerPlanB.js
> +			if (!this.renegotiationNeeded && (this.state === 'initial' || this.state === 'stable'))
i took this out to #224, marking this thread resolved.

2023-10-25 00:29 UTC, mildsunrise commented on lib/IncomingStream.js
> +						const source = SharedPointer(new Native.RTPIncomingSourceGroupShared(type,this.transport.GetTimeService()));
i took this out to #224, marking this thread resolved.

2023-10-25 00:29 UTC, mildsunrise commented on lib/ActiveSpeakerMultiplexer.js
> -			/**
i took this out to #223, marking this thread resolved.

2023-10-25 02:00 UTC, mildsunrise commented on lib/IncomingStream.js
> +		const promises = [...this.tracks.values()].map(track =>
i took this out to https://github.com/medooze/media-server-node/pull/225, marking this thread resolved.

2023-10-25 02:00 UTC, mildsunrise commented on lib/SDPManagerPlanB.js
> +			if (!this.renegotiationNeeded && (this.state === 'initial' || this.state === 'stable'))
i took this out to https://github.com/medooze/media-server-node/pull/225, marking this thread resolved.

2023-10-25 02:14 UTC, mildsunrise commented
I've taken most stuff out of this PR, which greatly reduces the amount of stuff to review.
there should be no refactors here now, i've only left the annotations / comments.

2023-10-25 08:35 UTC, murillo128 approved these changes
lgtm, minor comment

2023-10-25 08:35 UTC, murillo128 commented on lib/IncomingStreamTrackMirrored.js
> -	 * @returns {Map<String,Object>} Map with stats by encodingId
why remove the return type info?

2023-10-25 10:22 UTC, mildsunrise commented on lib/IncomingStreamTrackMirrored.js
> -	 * @returns {Map<String,Object>} Map with stats by encodingId
because it's incorrect :sweat_smile:

specifying the return type is optional, the type system can figure it out for you.
it's still good practice to specify it, but for simple functions which only call another function, it's not worth it imo.

2023-10-25 16:15 UTC, murillo128 commented on lib/IncomingStreamTrackMirrored.js
> -	 * @returns {Map<String,Object>} Map with stats by encodingId
i am mostly worried about docs

2023-10-25 17:09 UTC, mildsunrise commented on lib/IncomingStreamTrackMirrored.js
> -	 * @returns {Map<String,Object>} Map with stats by encodingId
typedoc shows precisely what the type system knows, regardless if you annotated it explicitly or not.
for example, in nal-extractor this function isn't annotated with a return type:

https://github.com/medooze/nal-extractor/blob/57fb85568b3a667d09b2dc26ede38497b872199c/lib/NalUnits.ts#L78-L83

but its documentation shows it precisely: https://medooze.github.io/nal-extractor/main/functions/NalUnits.parseNALU.html

are you okay with switching to typedoc to render the documentation?

2023-10-25 20:21 UTC, murillo128 commented on lib/IncomingStreamTrackMirrored.js
> -	 * @returns {Map<String,Object>} Map with stats by encodingId
yes, I am ok

2023-10-25 20:22 UTC, murillo128 commented
last rebase and I will merge, I promise.. :)

2023-10-26 01:24 UTC, mildsunrise commented
rebased and added some last-minute annotations in https://github.com/medooze/media-server-node/pull/217/commits/85a28b7ae7fc4c394de354c1df83a0ec87de5fdb

2023-10-26 06:52 UTC, murillo128 approved these changes
lgtm

2023-10-26 07:03 UTC, merged