DIOS-2863 Add codecs in use to getstatsdb
medooze/media-server-node pull request #232
Opened 2023-11-23 12:06 UTC by bcostdolby

2023-11-23 12:34 UTC, murillo128 requested changes

2023-11-23 12:34 UTC, murillo128 commented on lib/IncomingStreamTrack.js
> + * @property {number} [codec] Last codec in use
return a string and not a number, you can use `const char* GetNameForCodec(MediaFrame::Type media,DWORD codec)`
https://github.com/medooze/media-server/blob/master/include/codecs.h#L160C1-L160C71

2023-11-23 12:34 UTC, murillo128 commented on src/RTPIncomingSourceGroup.i
> +	DWORD codec;
you can extend the swig grapper to add a new atribute that does the number<->string conversion automatically

2023-11-23 15:57 UTC, mildsunrise commented on lib/IncomingStreamTrack.js
> + * @property {number} [codec] Last codec in use
agree, for consistency with the rest of the api we sould use strings

2023-11-24 05:34 UTC, bcostdolby commented on lib/IncomingStreamTrack.js
> + * @property {number} [codec] Last codec in use
done

2023-11-24 05:34 UTC, bcostdolby commented on src/RTPIncomingSourceGroup.i
> +	DWORD codec;
done

2023-11-24 07:25 UTC, murillo128 commented on lib/IncomingStreamTrack.js
> + * @property {string} [codec] Name of the codec last in use, media-server codecs.h for details
```suggestion
 * @property {string} [codec] Name of the codec last in use
```

2023-11-24 07:26 UTC, murillo128 approved these changes
lgtm

2023-11-24 08:58 UTC, murillo128 approved these changes
lgtm

2023-11-24 09:03 UTC, merged